
name: Qt Test run

on:
  push:
    branches: [ main ]
  #pull_request:
  #  branches: [ main ]
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build manually'     
        required: false
        default: false  

jobs:
  install_qt_clang_all:
    runs-on: windows-2019

    env:
      MANYLINUX_PYTHON_VERSION: '3.8'
      LLVM_INSTALL_DIR: '${{github.workspace}}/../libclang'
      VCINSTALLDIR: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/"

    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
    - name: Test only
      working-directory: ${{github.workspace}}
      run: |
        echo "set tmp ${{env.GITHUB_WORKSPACE}}"
        echo "ok ${{github.workspace}}"
        echo "MANYLINUX_PYTHON_VERSION $env.MANYLINUX_PYTHON_VERSION"
        echo "llvm=$env:LLVM_INSTALL_DIR"
        echo "Exe policy"
        Get-ExecutionPolicy
        # dir "c:\"
        #dir "C:\Program Files (x86)"
        #dir "C:\Program Files (x86)\Microsoft Visual Studio"
        #dir "C:\Program Files (x86)\Microsoft Visual Studio\2019"
        #dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise"
        $env:mystuff=Resolve-Path "${{github.workspace}}/.."
        echo "Mystuff is: $env:mystuff"
        dir "$env:mystuff"
        echo "mystuff=$env:mystuff" >> $env:GITHUB_ENV
        echo "action_state=yellow" >> $env:GITHUB_ENV
        # cmake --version
        mkdir ${{env.mystuff}}/tmp
        dir ${{env.mystuff}}
        $env:TMP="${{env.mystuff}}/tmp"
        $env:TEMP="${{env.mystuff}}/tmp"


    - name: visualstudio2017buildtools
      working-directory: ${{github.workspace}}
      run: |
        & choco install visualstudio2017buildtools

    - name: vswhere
      working-directory: ${{github.workspace}}
      run: |
        & 'C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere' "-products" "*" "-requires" "Microsoft.Component.MSBuild" "-property" "installationPath"
        "C:\ProgramData\Chocolatey\bin\vswhere.exe -latest -property installationPath"
        "C:\ProgramData\Chocolatey\bin\vswhere.exe -all"

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '[15.9]'  
        
    

        
