name: Qt Test run

on:
  push:
    branches: [ main ]
  #pull_request:
  #  branches: [ main ]
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build manually'     
        required: false
        default: false  
        
env:
    MANYLINUX_PYTHON_VERSION: '3.8'
    LLVM_INSTALL_DIR: '${{github.workspace}}/../libclang'
    VCINSTALLDIR: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/"
    CDIR: "C:/"
      
jobs:
  install_stuff:
    runs-on: windows-2019

    steps:
    - name: Patch Build
      working-directory: c:/
      run: |
        $env:mystuff=Resolve-Path "${{github.workspace}}/.."
        echo "Mystuff is: $env:mystuff"
        echo "mystuff=$env:mystuff" >> $env:GITHUB_ENV
        mkdir ${{env.mystuff}}/tmp
        dir ${{env.mystuff}}
        $env:TMP="${{env.mystuff}}/tmp"
        $env:TEMP="${{env.mystuff}}/tmp"
        #dir
        choco install  --no-progress wget
        dir "C:\Program Files (x86)\Microsoft Visual Studio"
        dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise"
        #wget -q --no-check-certificate http://gitty.sbcomputing.de/enterprise_2019.7z
        wget -q --no-check-certificate http://gitty.sbcomputing.de/bla.7z
        ren "C:\Program Files (x86)\Microsoft Visual Studio\2019" "C:\Program Files (x86)\Microsoft Visual Studio\2019_org"
        dir "C:\Program Files (x86)\Microsoft Visual Studio" 
        #& "c:/Program Files/7-Zip/7z.exe" "-y" "-Pbuild2019" "x" "enterprise_2019.7z" "-oC:/Program Files (x86)/Microsoft Visual Studio/"
        & "c:/Program Files/7-Zip/7z.exe" "-y" "-Pbuild2019" "x" "bla.7z" "-oC:/Program Files (x86)/Microsoft Visual Studio/"
        dir "C:\Program Files (x86)\Microsoft Visual Studio" 
  
  