name: Qt Test run

on:
  push:
    branches: [ main ]
  #pull_request:
  #  branches: [ main ]
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build manually'     
        required: false
        default: false  
        
  env:
      MANYLINUX_PYTHON_VERSION: '3.8'
      LLVM_INSTALL_DIR: '${{github.workspace}}/../libclang'
      VCINSTALLDIR: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/"
      CDIR: "C:/"
      
jobs:
  install_stuff:
    runs-on: windows-2019
    
    steps:
      - name: Install Software
      working-directory: ${{github.workspace}}
      run: |
        dir
        "c:/Program Files/7-Zip/7z.exe --version"
  
  