
name: Qt Test run

on:
  push:
    branches: [ main ]
  #pull_request:
  #  branches: [ main ]
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build manually'     
        required: false
        default: false  
  env:
      MANYLINUX_PYTHON_VERSION: '3.8'
      LLVM_INSTALL_DIR: '${{github.workspace}}/../libclang'
      VCINSTALLDIR: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/"
      CDIR: "C:/"
jobs:
  install_stuff:
    runs-on: windows-2019
    
    steps:
      - name: Install Software
      working-directory: c:/
      run: |
        dir
        "c:/Program Files/7-Zip/7z.exe --version"
        choco install  --no-progress wget
        dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise"
        wget --no-check-certificate http://gitty.sbcomputing.de/enterprise_2019.7z
        "c:/Program Files/7-Zip/7z.exe" "-Pbuild2019" "x" "enterprise_2019.7z" "-oC:/Program Files (x86)/Microsoft Visual Studio/"
        dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise"
  
  install_qt_clang_all:
    depends: install_stuff
    runs-on: windows-2019

    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
    - name: Mystuff
      working-directory: ${{github.workspace}}
      run: |
        $env:mystuff=Resolve-Path "${{github.workspace}}/.."
        echo "Mystuff is: $env:mystuff"
        echo "mystuff=$env:mystuff" >> $env:GITHUB_ENV
        mkdir ${{env.mystuff}}/tmp
        dir ${{env.mystuff}}
        $env:TMP="${{env.mystuff}}/tmp"
        $env:TEMP="${{env.mystuff}}/tmp"
      
    - name: Check env values
      working-directory: ${{github.workspace}}
      run: |
        echo "workspace is ${{github.workspace}}"
        echo "MANYLINUX_PYTHON_VERSION $env.MANYLINUX_PYTHON_VERSION"
        echo "llvm=$env:LLVM_INSTALL_DIR"
        echo "Exe policy"
        Get-ExecutionPolicy
        # dir "c:\"
        #dir "C:\Program Files (x86)"
        #dir "C:\Program Files (x86)\Microsoft Visual Studio"
        #dir "C:\Program Files (x86)\Microsoft Visual Studio\2019"
        dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise"



    - name: vswhere checks
      working-directory: ${{github.workspace}}
      run: |
        & 'C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere' "-products" "*" "-requires" "Microsoft.Component.MSBuild" "-property" "installationPath"
        & 'C:\ProgramData\Chocolatey\bin\vswhere.exe' '-latest' '-property' 'installationPath'
        & 'C:\ProgramData\Chocolatey\bin\vswhere.exe' '-all'
        & 'C:\ProgramData\Chocolatey\bin\vswhere.exe' '-products' '*' '-requires' 'Microsoft.Component.MSBuild' '-property' 'installationPath' '-latest'
        & 'C:\ProgramData\Chocolatey\bin\vswhere.exe' '-products' '*' '-requires' 'Microsoft.Component.MSBuild' '-property' 'installationPath'

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
